---
# yamllint configuration for Quaid Python project
# Extends default rules with project-specific adjustments

extends: default

# YAML files to consider
yaml-files:
  - "*.yaml"
  - "*.yml"
  - ".yamllint"

# Rule-specific configurations
rules:
  # 120 chars should be enough for modern screens, but warn only
  line-length:
    max: 120

  # Allow both indented and consistent sequence indentation
  indentation:
    indent-sequences: whatever

  # Comments are helpful, don't require document start
  document-start: enable

  # Be more lenient with empty lines
  empty-lines:
    max: 2

  # Braces and brackets spacing - be more lenient
  braces:
    max-spaces-inside: 1

  brackets:
    max-spaces-inside: 1

  # Commas and colons spacing - be more lenient
  commas: enable

  colons: enable

  # Hyphens spacing - be more lenient
  hyphens: enable

  # Comments indentation is nice but not critical
  comments-indentation: enable

  # Allow truthy values but warn about potential issues
  truthy: enable

  # Key ordering is nice but not critical - disabled for flexibility
  key-ordering: disable

# Files and directories to ignore
ignore: |
  .git/
  __pycache__/
  *.pyc
  .venv/
  venv/
  .quaid/
  build/
  dist/
  *.egg-info/
